export const REQUEST_ACTIVE_DEVICE_COUNTS = "REQUEST_ACTIVE_DEVICE_COUNTS";
export const RECEIVE_ACTIVE_DEVICE_COUNTS = "RECEIVE_ACTIVE_DEVICE_COUNTS";
export const RECEIVE_ACTIVE_DEVICE_COUNTS_ERRORS = "RECEIVE_ACTIVE_DEVICE_COUNTS_ERRORS";
