export const REQUEST_DISTRIBUTE_RELEASES = "REQUEST_DISTRIBUTE_RELEASES";
export const RECEIVE_DISTRIBUTE_RELEASES = "RECEIVE_DISTRIBUTE_RELEASES";
export const RECEIVE_DISTRIBUTE_RELEASES_ERROR = "RECEIVE_DISTRIBUTE_RELEASES_ERROR";
